function REQUEST(actionType) {
    return {
        type: actionType
    }
}
function SUCCESS(actionType, response) {
    return {
        type: actionType,
        payload: response
    }
}
function FAILURE(actionType, error) {
    return {
        type: actionType,
        payload: error
    }
}
const USER_REQUEST = {
    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    USER_BY_ROLE_REQUEST: 'USER_BY_ROLE_REQUEST',
    USER_BY_ROLE_SUCCESS: 'USER_BY_ROLE_SUCCESS',
    USER_BY_ROLE_FAILURE: 'USER_BY_ROLE_FAILURE',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',
    GET_ALL_USERS_REQUEST: 'GET_ALL_USERS_REQUEST',
    GET_ALL_USERS_SUCCESS: 'GET_ALL_USERS_SUCCESS',
    GET_ALL_USERS_FAILURE: 'GET_ALL_USERS_FAILURE',

    GET_ALL_CONSUMERS_REQUEST: 'GET_ALL_CONSUMERS_REQUEST',
    GET_ALL_CONSUMERS_SUCCESS: 'GET_ALL_CONSUMERS_SUCCESS',
    GET_ALL_CONSUMERS_FAILURE: 'GET_ALL_CONSUMERS_FAILURE',

    GET_ALL_ADMINS_REQUEST: 'GET_ALL_ADMINS_REQUEST',
    GET_ALL_ADMINS_SUCCESS: 'GET_ALL_ADMINS_SUCCESS',
    GET_ALL_ADMINS_FAILURE: 'GET_ALL_ADMINS_FAILURE',

    RESET_USER_DATA: 'RESET_USER_DATA',

    GET_USER_REQUEST: 'GET_USER_REQUEST',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    GET_USER_FAILURE: 'GET_USER_FAILURE',

    EDIT_USER_REQUEST: 'EDIT_USER_REQUEST',
    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAILURE: 'EDIT_USER_FAILURE',

    DELETE_USER_REQUEST: 'DELETE_USER_REQUEST',
    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILURE: 'DELETE_USER_FAILURE',

    UPDATE_PASSWORD_REQUEST: 'UPDATE_PASSWORD_REQUEST',
    UPDATE_PASSWORD_SUCCESS: 'UPDATE_PASSWORD_SUCCESS',
    UPDATE_PASSWORD_FAILURE: 'UPDATE_PASSWORD_FAILURE',
    
    CREATE_REQUEST: 'CREATER_REQUEST',
    CREATE_SUCCESS: 'CREATE_SUCCESS',
    CREATE_FAILURE: 'CREATE_FAILURE',
}

const PRODUCT_REQUEST = {
    ADD_PRODUCT_REQUEST: 'ADD_PRODUCT_REQUEST',
    ADD_PRODUCT_SUCCESS: 'ADD_PRODUCT_SUCCESS',
    ADD_PRODUCT_FAILURE: 'ADD_PRODUCT_FAILURE',

    CREATE_CATEGORY_REQUEST: 'CREATE_CATEGORY_REQUEST',
    CREATE_CATEGORY_SUCCESS: 'CREATE_CATEGORY_SUCCESS',
    CREATE_CATEGORY_FAILURE: 'CREATE_CATEGORY_FAILURE',

    CREATE_VARIANT_REQUEST: 'CREATE_VARIANT_REQUEST',
    CREATE_VARIANT_SUCCESS: 'CREATE_VARIANT_SUCCESS',
    CREATE_VARIANT_FAILURE: 'CREATE_VARIANT_FAILURE',

    GET_ALL_PRODUCTS_REQUEST: 'GET_ALL_PRODUCTS_REQUEST',
    GET_ALL_PRODUCTS_SUCCESS: 'GET_ALL_PRODUCTS_SUCCESS',
    GET_ALL_PRODUCTS_FAILURE: 'GET_ALL_PRODUCTS_FAILURE',

    GET_ALL_CATEGORIES_REQUEST: 'GET_ALL_CATEGORIES_REQUEST',
    GET_ALL_CATEGORIES_SUCCESS: 'GET_ALL_CATEGORIES_SUCCESS',
    GET_ALL_CATEGORIES_FAILURE: 'GET_ALL_CATEGORIES_FAILURE',


    GET_PRODUCT_BY_ID_REQUEST: 'GET_PRODUCT_BY_ID_REQUEST',
    GET_PRODUCT_BY_ID_SUCCESS: 'GET_PRODUCT_BY_ID_SUCCESS',
    GET_PRODUCT_BY_ID_FAILURE: 'GET_PRODUCT_BY_ID_FAILURE',

    EDIT_PRODUCT_REQUEST: 'EDIT_PRODUCT_REQUEST',
    EDIT_PRODUCT_SUCCESS: 'EDIT_PRODUCT_SUCCESS',
    EDIT_PRODUCT_FAILURE: 'EDIT_PRODUCT_FAILURE',

    DELETE_PRODUCT_REQUEST: 'DELETE_PRODUCT_REQUEST',
    DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
    DELETE_PRODUCT_FAILURE: 'DELETE_PRODUCT_FAILURE',

    GET_CATEGORY_BY_ID_REQUEST: 'GET_CATEGORY_BY_ID_REQUEST',
    GET_CATEGORY_BY_ID_SUCCESS: 'GET_CATEGORY_BY_ID_SUCCESS',
    GET_CATEGORY_BY_ID_FAILURE: 'GET_CATEGORY_BY_ID_FAILURE',

    UPDATE_CATEGORY_REQUEST: 'UPDATE_CATEGORY_REQUEST',
    UPDATE_CATEGORY_SUCCESS: 'UPDATE_CATEGORY_SUCCESS',
    UPDATE_CATEGORY_FAILURE: 'UPDATE_CATEGORY_FAILURE',

    DELETE_CATEGORY_REQUEST: 'DELETE_CATEGORY_REQUEST',
    DELETE_CATEGORY_SUCCESS: 'DELETE_CATEGORY_SUCCESS',
    DELETE_CATEGORY_FAILURE: 'DELETE_CATEGORY_FAILURE',
}

const FABRIC_REQUEST = {
    ADD_FABRIC_REQUEST: 'ADD_FABRIC_REQUEST',
    ADD_FABRIC_SUCCESS: 'ADD_FABRIC_SUCCESS',
    ADD_FABRIC_FAILURE: 'ADD_FABRIC_FAILURE',
    EDIT_FABRIC_REQUEST: 'EDIT_FABRIC_REQUEST',
    EDIT_FABRIC_SUCCESS: 'EDIT_FABRIC_SUCCESS',
    EDIT_FABRIC_FAILURE: 'EDIT_FABRIC_FAILURE',
    GET_ALL_FABRIC_REQUEST: 'GET_ALL_FABRIC_REQUEST',
    GET_ALL_FABRIC_SUCCESS: 'GET_ALL_FABRIC_SUCCESS',
    GET_ALL_FABRIC_FAILURE: 'GET_ALL_FABRIC_FAILURE',
    GET_FABRIC_REQUEST: 'GET_FABRIC_REQUEST',
    GET_FABRIC_SUCCESS: 'GET_FABRIC_SUCCESS',
    GET_FABRIC_FAILURE: 'GET_FABRIC_FAILURE',
    REMOVE_FABRIC_REQUEST: 'REMOVE_FABRIC_REQUEST',
    REMOVE_FABRIC_SUCCESS: 'REMOVE_FABRIC_SUCCESS',
    REMOVE_FABRIC_FAILURE: 'REMOVE_FABRIC_FAILURE',
}

const SIZE_REQUEST = {
    SIZE_LIST: 'SIZE_LIST',
    SIZE_CHANGE: 'SIZE_CHANGE',
    RESET_ITEM_SIZE_LIST: 'RESET_ITEM_SIZE_LIST',
    ADD_ITEM_SIZE_LIST: 'ADD_ITEM_SIZE_LIST',
    REMOVE_ITEM_SIZE_LIST: 'REMOVE_ITEM_SIZE_LIST',
    ADD_SIZE_REQUEST: 'ADD_SIZE_REQUEST',
    ADD_SIZE_SUCCESS: 'ADD_SIZE_SUCCESS',
    ADD_SIZE_FAILURE: 'ADD_SIZE_FAILURE',
    EDIT_SIZE_REQUEST: 'EDIT_SIZE_REQUEST',
    EDIT_SIZE_SUCCESS: 'EDIT_SIZE_SUCCESS',
    EDIT_SIZE_FAILURE: 'EDIT_SIZE_FAILURE',
    GET_ALL_SIZES_REQUEST: 'GET_ALL_SIZES_REQUEST',
    GET_ALL_SIZES_SUCCESS: 'GET_ALL_SIZES_SUCCESS',
    GET_ALL_SIZES_FAILURE: 'GET_ALL_SIZES_FAILURE',
    GET_SIZE_REQUEST: 'GET_SIZE_REQUEST',
    GET_SIZE_SUCCESS: 'GET_SIZE_SUCCESS',
    GET_SIZE_FAILURE: 'GET_SIZE_FAILURE',
    REMOVE_SIZE_REQUEST: 'REMOVE_SIZE_REQUEST',
    REMOVE_SIZE_SUCCESS: 'REMOVE_SIZE_SUCCESS',
    REMOVE_SIZE_FAILURE: 'REMOVE_SIZE_FAILURE',
    GET_SIZE_BY_ITEM_REQUEST: 'GET_SIZE_BY_ITEM_REQUEST',
    GET_SIZE_BY_ITEM_SUCCESS: 'GET_SIZE_BY_ITEM_SUCCESS',
    GET_SIZE_BY_ITEM_FAILURE: 'GET_SIZE_BY_ITEM_FAILURE',
}

const ORDER_REQUEST = {
    ADD_ORDER_REQUEST: 'ADD_ORDER_REQUEST',
    ADD_ORDER_SUCCESS: 'ADD_ORDER_SUCCESS',
    ADD_ORDER_FAILURE: 'ADD_ORDER_FAILURE',
    EDIT_ORDER_REQUEST: 'EDIT_ORDER_REQUEST',
    EDIT_ORDER_SUCCESS: 'EDIT_ORDER_SUCCESS',
    EDIT_ORDER_FAILURE: 'EDIT_ORDER_FAILURE',
    GET_ALL_ORDERS_REQUEST: 'GET_ALL_ORDERS_REQUEST',
    GET_ALL_ORDERS_SUCCESS: 'GET_ALL_ORDERS_SUCCESS',
    GET_ALL_ORDERS_FAILURE: 'GET_ALL_ORDERS_FAILURE',
    GET_ORDER_REQUEST: 'GET_ORDER_REQUEST',
    GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS',
    GET_ORDER_FAILURE: 'GET_ORDER_FAILURE',
    REMOVE_ORDER_REQUEST: 'REMOVE_ORDER_REQUEST',
    REMOVE_ORDER_SUCCESS: 'REMOVE_ORDER_SUCCESS',
    REMOVE_ORDER_FAILURE: 'REMOVE_ORDER_FAILURE',
    GET_ORDER_BY_FILTER_REQUEST: 'GET_ORDER_BY_FILTER_REQUEST',
    GET_ORDER_BY_FILTER_SUCCESS: 'GET_ORDER_BY_FILTER_SUCCESS',
    GET_ORDER_BY_FILTER_FAILURE: 'GET_ORDER_BY_FILTER_FAILURE',
    GET_ALL_ITEMS_AND_FABRICS_REQUEST: 'GET_ALL_ITEMS_AND_FABRICS_REQUEST',
    GET_ALL_ITEMS_AND_FABRICS_SUCCESS: 'GET_ALL_ITEMS_AND_FABRICS_SUCCESS',
    GET_ALL_ITEMS_AND_FABRICS_FAILURE: 'GET_ALL_ITEMS_AND_FABRICS_FAILURE',
    RESET_ORDER_LIST: 'RESET_ORDER_LIST',
    ADD_ORDER_LIST: 'ADD_ORDER_LIST',
    REMOVE_ORDER_LIST: 'REMOVE_ORDER_LIST',

    // New
    CREATE_PURCHASE_ORDER_REQUEST: 'CREATE_PURCHASE_ORDER_REQUEST',
    CREATE_PURCHASE_ORDER_SUCCESS: 'CREATE_PURCHASE_ORDER_SUCCESS',
    CREATE_PURCHASE_ORDER_FAILURE: 'CREATE_PURCHASE_ORDER_FAILURE',

    // Added GET_ALL_PURCHASE_ORDERS actions
    GET_ALL_PURCHASE_ORDERS_REQUEST: 'GET_ALL_PURCHASE_ORDERS_REQUEST',
    GET_ALL_PURCHASE_ORDERS_SUCCESS: 'GET_ALL_PURCHASE_ORDERS_SUCCESS',
    GET_ALL_PURCHASE_ORDERS_FAILURE: 'GET_ALL_PURCHASE_ORDERS_FAILURE',

    // New action for getting a purchase order by ID
    GET_PURCHASE_ORDER_BY_ID_REQUEST: 'GET_PURCHASE_ORDER_BY_ID_REQUEST',
    GET_PURCHASE_ORDER_BY_ID_SUCCESS: 'GET_PURCHASE_ORDER_BY_ID_SUCCESS',
    GET_PURCHASE_ORDER_BY_ID_FAILURE: 'GET_PURCHASE_ORDER_BY_ID_FAILURE',

    // New actions for updating a purchase order
    UPDATE_PURCHASE_ORDER_REQUEST: 'UPDATE_PURCHASE_ORDER_REQUEST',
    UPDATE_PURCHASE_ORDER_SUCCESS: 'UPDATE_PURCHASE_ORDER_SUCCESS',
    UPDATE_PURCHASE_ORDER_FAILURE: 'UPDATE_PURCHASE_ORDER_FAILURE',

    // New actions for deleting a purchase order
    DELETE_PURCHASE_ORDER_REQUEST: 'DELETE_PURCHASE_ORDER_REQUEST',
    DELETE_PURCHASE_ORDER_SUCCESS: 'DELETE_PURCHASE_ORDER_SUCCESS',
    DELETE_PURCHASE_ORDER_FAILURE: 'DELETE_PURCHASE_ORDER_FAILURE',

}
const ITEM_REQUEST = {
    ADD_ITEM_REQUEST: 'ADD_ITEM_REQUEST',
    ADD_ITEM_SUCCESS: 'ADD_ITEM_SUCCESS',
    ADD_ITEM_FAILURE: 'ADD_ITEM_FAILURE',
    EDIT_ITEM_REQUEST: 'EDIT_ITEM_REQUEST',
    EDIT_ITEM_SUCCESS: 'EDIT_ITEM_SUCCESS',
    EDIT_ITEM_FAILURE: 'EDIT_ITEM_FAILURE',
    GET_ALL_ITEMS_REQUEST: 'GET_ALL_ITEMS_REQUEST',
    GET_ALL_ITEMS_SUCCESS: 'GET_ALL_ITEMS_SUCCESS',
    GET_ALL_ITEMS_FAILURE: 'GET_ALL_ITEMS_FAILURE',
    GET_ITEM_REQUEST: 'GET_ITEM_REQUEST',
    GET_ITEM_SUCCESS: 'GET_ITEM_SUCCESS',
    GET_ITEM_FAILURE: 'GET_ITEM_FAILURE',
    REMOVE_ITEM_REQUEST: 'REMOVE_ITEM_REQUEST',
    REMOVE_ITEM_SUCCESS: 'REMOVE_ITEM_SUCCESS',
    REMOVE_ITEM_FAILURE: 'REMOVE_ITEM_FAILURE',
    GET_ALL_USER_ITEMS_REQUEST: 'GET_ALL_USER_ITEMS_REQUEST',
    GET_ALL_USER_ITEMS_SUCCESS: 'GET_ALL_USER_ITEMS_SUCCESS',
    GET_ALL_USER_ITEMS_FAILURE: 'GET_ALL_USER_ITEMS_FAILURE',
    ADD_USER_ITEMS_REQUEST: 'ADD_USER_ITEMS_REQUEST',
    ADD_USER_ITEMS_SUCCESS: 'ADD_USER_ITEMS_SUCCESS',
    ADD_USER_ITEMS_FAILURE: 'ADD_USER_ITEMS_FAILURE',
    REMOVE_USER_ITEM_REQUEST: 'REMOVE_USER_ITEM_REQUEST',
    REMOVE_USER_ITEM_SUCCESS: 'REMOVE_USER_ITEM_SUCCESS',
    REMOVE_USER_ITEM_FAILURE: 'REMOVE_USER_ITEM_FAILURE',
}

export {
    REQUEST,
    SUCCESS,
    FAILURE,
    USER_REQUEST,
    PRODUCT_REQUEST,
    ORDER_REQUEST,
    FABRIC_REQUEST,
    SIZE_REQUEST,
    ITEM_REQUEST
}